config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cafe#index"
  get "/order", to: "orders#index", as: "order_items"
  get "order/new", to: "order_items#new", as:"new_order_item"
  post "/order", to: "order_items#create"
  get "order_items/:id/edit", to: "order_items#edit", as:
  "edit_order_item"
  resources :order_items, only: %i[edit update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
    
end
  

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cafe_controller.rb
class CafeController < ApplicationController
  
    def index
        @menu = MenuItem.all
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
    def new
        @order_item = OrderItem.new
        @order_item.name = params[:item_name]
    end

    def create
        @order_item = OrderItem.new
        @order_item.name = params[:order_item][:name]
        @order_item.quantity = params[:order_item][:quantity]
       
        if @order_item.save
          redirect_to order_items_path
        else
          render "new"
        end
    end

    def edit
        @order_item = OrderItem.find(params[:id])
    end
    
    def update
        @order_item = OrderItem.find(params[:id])
        @order_item.quantity = params[:order_item][:quantity]
        if @order_item.save
            redirect_to order_items_path
        else
            render "edit"
        end
    end

    def destroy
        OrderItem.destroy(params[:id])
        redirect_to order_items_path
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
        @order = OrderItem.all
        @order_total = total
    end
    def total
        sum = 0
        menu = MenuItem.all
        @order.each do |order_item|
          sum += order_item.quantity * menu.where(name: order_item.name).first.price
        end
        return sum
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafe_helper.rb
module CafeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/cafe/index.html.erb
<h1>Welcome to Coder Cafe!</h1>

<table>
 <tr>
   <th>Item</th>
   <th>Price</th>
 </tr>
 <% @menu.each do |menu_item| %>
    
    <tr>
        <td><%= menu_item.name%></td>
        <td><%= "$%.2f" % menu_item.price%></td>
        <td><%= link_to 'Order', new_order_item_path(:item_name => menu_item.name)
        %></td>
    </tr>
    <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  # <link rel="stylesheet" href="./assets/stylesheets/styles.css" />
    <title>Cafe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "shared/navigation"%>
  <section class="container">
    <%= yield %>
    </section>
  </body>
</html>

app/views/order_items/edit.html.erb
<%=form_with model:@order_item, class: "form-class" do |form| %>
    <table>
      <tr>
        <td><%= "How many #{@order_item.name}s would you like?"%></td>
        <td><%= form.hidden_field :name%></td>
      </tr>
      <tr>
        <td><%= label(:quantity,"Qty")%>
        <%= form.number_field :quantity, min:1, value: @order_item.quantity%></td>
      </tr>
      <tr>
        <td><%= form.submit "Edit order", class: "button-class"%></td>
      </tr>
    </table>
   <%end%>

app/views/order_items/new.html.erb
<%=form_with model:@order_item, class: "form-class" do |form| %>
    <table>
      <tr>
        <td><%= "How many #{@order_item.name}s would you like?"%></td>
        <td><%= form.hidden_field :name%></td>
      </tr>
      <tr>
        <td><%= label(:quantity,"Qty")%>
        <%= form.number_field :quantity, min:1, value: 1%></td>
      </tr>
      <tr>
        <td><%= form.submit "Add to order", class: "button-class"%></td>
      </tr>
    </table>
   <%end%>

app/views/orders/index.html.erb
<h1>Your Order</h1>
<table>
<tr>
<th>Quantity</th>
<th>Item</th>
</tr>
<%if @order%>
 <% @order.each do |order_item| %>
   <tr>
     <td><%= order_item.quantity %></td>
     <td><%= order_item.name %></td>
     <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
     <td><%= link_to 'Delete', order_item,  method: :delete, data: { confirm: 'Are you sure?' 
     } %></td>
     
   </tr>
   <%end%>
   <tr>
     <th>Total</th>
     <th><%= "$%.2f" % @order_total %></th>
   </tr>
 <%end%>
 </table>

app/views/shared/_navigation.html.erb
<div id="topnav">
 <%=link_to 'Cafe Menu', root_path%>
 <%=link_to 'My Order', order_items_path%>
</div>